<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Departement extends \App\Entity\Departement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depId', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depNom', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depDescription', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depAuteurcreation', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depDatecreation', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depAuteurchangement', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depDatechangement'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depId', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depNom', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depDescription', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depAuteurcreation', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depDatecreation', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depAuteurchangement', '' . "\0" . 'App\\Entity\\Departement' . "\0" . 'depDatechangement'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Departement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDepId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDepId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepId', []);

        return parent::getDepId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDepNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepNom', []);

        return parent::getDepNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepNom(string $depNom): \App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepNom', [$depNom]);

        return parent::setDepNom($depNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepDescription', []);

        return parent::getDepDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepDescription(?string $depDescription): \App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepDescription', [$depDescription]);

        return parent::setDepDescription($depDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepAuteurcreation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepAuteurcreation', []);

        return parent::getDepAuteurcreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepAuteurcreation(string $depAuteurcreation): \App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepAuteurcreation', [$depAuteurcreation]);

        return parent::setDepAuteurcreation($depAuteurcreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepDatecreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepDatecreation', []);

        return parent::getDepDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepDatecreation(\DateTimeInterface $depDatecreation): \App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepDatecreation', [$depDatecreation]);

        return parent::setDepDatecreation($depDatecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepAuteurchangement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepAuteurchangement', []);

        return parent::getDepAuteurchangement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepAuteurchangement(string $depAuteurchangement): \App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepAuteurchangement', [$depAuteurchangement]);

        return parent::setDepAuteurchangement($depAuteurchangement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepDatechangement(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepDatechangement', []);

        return parent::getDepDatechangement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepDatechangement(\DateTimeInterface $depDatechangement): \App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepDatechangement', [$depDatechangement]);

        return parent::setDepDatechangement($depDatechangement);
    }

}
