<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Niveaulisteministerielle extends \App\Entity\Niveaulisteministerielle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminId', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminName', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminDescription', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminAuteurcreation', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminDatecreation', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminAuteurchangement', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminDatechangement'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminId', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminName', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminDescription', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminAuteurcreation', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminDatecreation', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminAuteurchangement', '' . "\0" . 'App\\Entity\\Niveaulisteministerielle' . "\0" . 'nivlisminDatechangement'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Niveaulisteministerielle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNivlisminId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNivlisminId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminId', []);

        return parent::getNivlisminId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNivlisminName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminName', []);

        return parent::getNivlisminName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivlisminName(string $nivlisminName): \App\Entity\Niveaulisteministerielle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivlisminName', [$nivlisminName]);

        return parent::setNivlisminName($nivlisminName);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivlisminDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminDescription', []);

        return parent::getNivlisminDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivlisminDescription(?string $nivlisminDescription): \App\Entity\Niveaulisteministerielle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivlisminDescription', [$nivlisminDescription]);

        return parent::setNivlisminDescription($nivlisminDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivlisminAuteurcreation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminAuteurcreation', []);

        return parent::getNivlisminAuteurcreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivlisminAuteurcreation(string $nivlisminAuteurcreation): \App\Entity\Niveaulisteministerielle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivlisminAuteurcreation', [$nivlisminAuteurcreation]);

        return parent::setNivlisminAuteurcreation($nivlisminAuteurcreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivlisminDatecreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminDatecreation', []);

        return parent::getNivlisminDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivlisminDatecreation(\DateTimeInterface $nivlisminDatecreation): \App\Entity\Niveaulisteministerielle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivlisminDatecreation', [$nivlisminDatecreation]);

        return parent::setNivlisminDatecreation($nivlisminDatecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivlisminAuteurchangement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminAuteurchangement', []);

        return parent::getNivlisminAuteurchangement();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivlisminAuteurchangement(string $nivlisminAuteurchangement): \App\Entity\Niveaulisteministerielle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivlisminAuteurchangement', [$nivlisminAuteurchangement]);

        return parent::setNivlisminAuteurchangement($nivlisminAuteurchangement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivlisminDatechangement(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivlisminDatechangement', []);

        return parent::getNivlisminDatechangement();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivlisminDatechangement(\DateTimeInterface $nivlisminDatechangement): \App\Entity\Niveaulisteministerielle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivlisminDatechangement', [$nivlisminDatechangement]);

        return parent::setNivlisminDatechangement($nivlisminDatechangement);
    }

}
