<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5xT3nu_' shared service.

return $this->privates['.service_locator.5xT3nu_'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('fileUploader' => function (): \App\Service\FileUploader {
    return ($this->privates['App\Service\FileUploader'] ?? $this->privates['App\Service\FileUploader'] = new \App\Service\FileUploader(($this->targetDirs[3].'/public/uploads/fichiers')));
}, 'logger' => function () {
    return ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());
}));
