<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIZcM4ww\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIZcM4ww/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIZcM4ww.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIZcM4ww\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIZcM4ww\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IZcM4ww',
    'container.build_id' => 'e8ce6e7e',
    'container.build_time' => 1542013352,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIZcM4ww');
