<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27hCPvZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27hCPvZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container27hCPvZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container27hCPvZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container27hCPvZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => '27hCPvZ',
    'container.build_id' => 'febaf7d2',
    'container.build_time' => 1541702059,
), __DIR__.\DIRECTORY_SEPARATOR.'Container27hCPvZ');
