<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ3QVRe5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ3QVRe5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ3QVRe5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQ3QVRe5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQ3QVRe5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Q3QVRe5',
    'container.build_id' => '752847ef',
    'container.build_time' => 1542036943,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ3QVRe5');
